### ISSUE TITLE
O laravel-debug-bar está ativo em produção

### ISSUE THREAD

**Issue by tadeubdev** [calvinchiulele/idai_africa#12]
Não consegui achar aonde ele está chamando o `laravel-debug-bar`, mas creio que ele não deveria estar em produção.

![image](https://user-images.githubusercontent.com/4499999/56926692-b4b01780-6aa8-11e9-9efe-70033418dad5.png)

Se vocês estiverem utilizando o [barryvdh/laravel-debugbar](https://github.com/barryvdh/laravel-debugbar), eles estão dizendo que por padrão o APP_DEBUG vem como `true`. Veja no README [deles](https://github.com/barryvdh/laravel-debugbar).
*\* Dá pra colocar no `.env` também...*

**Comment by joseseie** [comment]
Até agora? Precisamos de ver isso com urgência.

**Comment by thatfiredev** [comment]
Olá @tadeubarbosa 

Creio que tens o repositório errado. A versão que acedeste (a atual que está em produção) está no nosso repositório anterior [mozdevz/idai.africa](https://github.com/mozdevz/idai.africa).

Quando terminarmos os trabalhos neste repositório iremos enviar para produção. E o repositório anterior será abandonado.

**Comment by tadeubdev** [comment]
Ah sim, @rosariopfernandes , entendi!
